'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';

type Business={id:string;name:string;slug:string;status:string;phone:string|null;email:string|null;address:string|null;description:string|null};
const statusLabels:Record<string,string>={active:'Активна',pending:'На модерации',suspended:'Приостановлена',rejected:'Отклонена'};

export default function EditBusinessPage(){
 const {id}=useParams<{id:string}>(); const router=useRouter();
 const [business,setBusiness]=useState<Business|null>(null); const [form,setForm]=useState({name:'',phone:'',email:'',address:'',description:'',status:'active'}); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 useEffect(()=>{fetch(`/api/admin/businesses/detail?id=${encodeURIComponent(id)}`).then(async r=>{const x=await r.json();if(r.status===403){router.replace('/admin/login');return}if(!r.ok)throw new Error(x.error);setBusiness(x.business);if(x.business)setForm({name:x.business.name||'',phone:x.business.phone||'',email:x.business.email||'',address:x.business.address||'',description:x.business.description||'',status:x.business.status||'active'});}).catch(e=>setError(e instanceof Error?e.message:'Не удалось загрузить СТО'))},[id,router]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');setError('');try{const r=await fetch('/api/admin/businesses/update',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,...form})});const x=await r.json();if(r.status===403){router.replace('/admin/login');return}if(!r.ok)throw new Error(x.error||'SAVE_FAILED');setBusiness(x.business);setMessage('Сохранено. Изменение записано в аудит.');}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить')}finally{setBusy(false)}}
 if(error&&!business)return <main className="content"><div className="card error">{error}</div></main>;
 if(!business)return <main className="content"><div className="card">Загружаем…</div></main>;
 return <main className="page"><header className="hero"><div className="hero-inner"><span className="eyebrow">STO NSK · Admin</span><h1>Редактирование СТО</h1><p>{business.name}</p></div></header><div className="content"><div className="toolbar"><a className="pill" href={`/admin/businesses/${id}`}>← Карточка СТО</a></div><section className="card" style={{marginTop:16}}><form onSubmit={save} style={{display:'grid',gap:12}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><label>Название<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required /></label><label>Телефон<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} /></label><label>Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} type="email" /></label><label>Статус<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><label>Адрес<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} /></label><label>Описание<textarea rows={6} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} /></label>{message&&<div className="card">{message}</div>}{error&&<div className="card error">{error}</div>}<button className="primary" disabled={busy} type="submit">{busy?'Сохраняем…':'Сохранить'}</button></form></section></div><style jsx>{`label{display:grid;gap:6px;font-weight:600}input,select,textarea{width:100%;box-sizing:border-box;padding:11px 12px;border:1px solid rgba(0,0,0,.12);border-radius:10px;background:#fff;font:inherit}@media(max-width:700px){form>div:first-child{grid-template-columns:1fr!important}}`}</style></main>;
}
