'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';

type Detail={business?:{id:string;name:string;slug:string;status:string;rating:number|null;review_count:number;address:string|null;phone:string|null;email:string|null;description:string|null;created_at:string};services:Array<{id:string;price:number;duration_minutes:number;is_active:boolean;service?:{name:string;slug:string}}>;employees:Array<{id:string;name:string;position:string|null;is_active:boolean}>;workstations:Array<{id:string;name:string;status:string}>;appointments:Array<{id:string;starts_at:string;ends_at:string;status:string;user?:{display_name:string|null;phone:string|null};service?:{service?:{name:string}}}>};
const labels:Record<string,string>={PENDING:'Ожидает',CONFIRMED:'Подтверждена',ARRIVED:'Прибыл',IN_SERVICE:'В работе',READY:'Готов',COMPLETED:'Завершена',CANCELLED:'Отменена',NO_SHOW:'Неявка'};
const statusLabels:Record<string,string>={active:'Активна',pending:'На модерации',blocked:'Заблокирована',suspended:'Приостановлена'};
export default function AdminBusinessDetail(){
 const {id}=useParams<{id:string}>();const router=useRouter();const [data,setData]=useState<Detail|null>(null);const [error,setError]=useState('');
 useEffect(()=>{fetch(`/api/admin/businesses/detail?id=${encodeURIComponent(id)}`).then(async r=>{const x=await r.json();if(r.status===403){router.replace('/admin/login');return}if(!r.ok)throw new Error(x.error);setData(x)}).catch(()=>setError('Не удалось загрузить карточку СТО.'))},[id,router]);
 if(error)return <main className="content"><div className="card error">{error}</div><a className="primary" href="/admin/businesses">Вернуться к СТО</a></main>;
 if(!data?.business)return <main className="content"><div className="card">Загружаем карточку СТО…</div></main>;
 const b=data.business;
 return <main className="page"><header className="hero"><div className="hero-inner"><span className="eyebrow">STO NSK · Управление СТО</span><h1>{b.name}</h1><p>{b.address||'Адрес не указан'} · статус <strong>{statusLabels[b.status]||b.status}</strong></p></div></header><div className="content">
 <div className="toolbar"><a className="pill" href="/admin/businesses">← Все СТО</a><a className="pill" href={`/admin/businesses/${b.id}/edit`}>Редактировать</a><a className="pill" href={`/novosibirsk/sto/${b.slug}`}>Публичная страница</a></div>
 <div className="feature-grid"><div className="feature"><strong>Рейтинг</strong><span style={{fontSize:28,fontWeight:800}}>★ {b.rating??0}</span><span className="muted">{b.review_count??0} отзывов</span></div><div className="feature"><strong>Услуги</strong><span style={{fontSize:28,fontWeight:800}}>{data.services.length}</span></div><div className="feature"><strong>Сотрудники</strong><span style={{fontSize:28,fontWeight:800}}>{data.employees.length}</span></div><div className="feature"><strong>Посты</strong><span style={{fontSize:28,fontWeight:800}}>{data.workstations.length}</span></div><div className="feature"><strong>Последние записи</strong><span style={{fontSize:28,fontWeight:800}}>{data.appointments.length}</span></div></div>
 <div className="feature-grid" style={{marginTop:16}}><section className="card"><div className="toolbar"><h2>Контакты</h2><span className="pill">{statusLabels[b.status]||b.status}</span></div><div className="service-row"><strong>Телефон</strong><span>{b.phone||'—'}</span></div><div className="service-row"><strong>Email</strong><span>{b.email||'—'}</span></div><div className="service-row"><strong>Адрес</strong><span>{b.address||'—'}</span></div>{b.description&&<p className="muted" style={{marginTop:12}}>{b.description}</p>}</section><section className="card"><h2>Быстрые действия</h2><div style={{display:'grid',gap:8,marginTop:12}}><a className="primary" href={`/admin/businesses/${b.id}/edit`}>Редактировать СТО</a><a className="pill" href={`/business?businessId=${b.id}`}>Кабинет СТО</a><a className="pill" href="/admin/audit">Открыть аудит</a></div></section></div>
 <section className="card" style={{marginTop:16}}><div className="toolbar"><div><h2>Услуги</h2><div className="muted">Активные и архивные услуги СТО</div></div><span className="pill">{data.services.length}</span></div>{data.services.length?data.services.map(s=><div className="service-row" key={s.id}><div style={{flex:1}}><strong>{s.service?.name||'Услуга'}</strong><div className="muted">{s.duration_minutes} мин · {s.price} ₽</div></div><span className="pill">{s.is_active?'Активна':'Выключена'}</span></div>):<div className="empty">Услуг нет.</div>}</section>
 <section className="card" style={{marginTop:16}}><div className="toolbar"><div><h2>Сотрудники</h2><div className="muted">Команда, которая принимает клиентов</div></div><span className="pill">{data.employees.length}</span></div>{data.employees.length?data.employees.map(e=><div className="service-row" key={e.id}><div style={{flex:1}}><strong>{e.name}</strong><div className="muted">{e.position||'Должность не указана'}</div></div><span className="pill">{e.is_active?'Активен':'Неактивен'}</span></div>):<div className="empty">Сотрудников нет.</div>}</section>
 <section className="card" style={{marginTop:16}}><div className="toolbar"><div><h2>Посты</h2><div className="muted">Рабочие места и их текущий статус</div></div><span className="pill">{data.workstations.length}</span></div>{data.workstations.length?data.workstations.map(w=><div className="service-row" key={w.id}><strong>{w.name}</strong><span className="pill">{w.status}</span></div>):<div className="empty">Постов нет.</div>}</section>
 <section className="card" style={{marginTop:16}}><div className="toolbar"><div><h2>Последние записи</h2><div className="muted">Последние 25 записей по СТО</div></div><span className="pill">{data.appointments.length}</span></div>{data.appointments.length?data.appointments.map(a=><div className="service-row" key={a.id}><div style={{flex:1}}><strong>{a.user?.display_name||'Клиент'}</strong><div className="muted">{a.service?.service?.name||'Услуга'} · {new Date(a.starts_at).toLocaleString('ru-RU',{dateStyle:'medium',timeStyle:'short'})}</div></div><span className="pill">{labels[a.status]||a.status}</span></div>):<div className="empty">Записей нет.</div>}</section>
 </div></main>;
}
