'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';

type Detail={business?:{id:string;name:string;slug:string;status:string;rating:number|null;review_count:number;address:string|null;phone:string|null;email:string|null;description:string|null;created_at:string};services:Array<{id:string;price:number;duration_minutes:number;is_active:boolean;service?:{name:string;slug:string}}>;employees:Array<{id:string;name:string;position:string|null;is_active:boolean}>;workstations:Array<{id:string;name:string;status:string}>;appointments:Array<{id:string;starts_at:string;ends_at:string;status:string;user?:{display_name:string|null;phone:string|null};service?:{service?:{name:string}}}>};
const labels:Record<string,string>={PENDING:'Ожидает',CONFIRMED:'Подтверждена',ARRIVED:'Прибыл',IN_SERVICE:'В работе',READY:'Готов',COMPLETED:'Завершена',CANCELLED:'Отменена',NO_SHOW:'Неявка'};
const statusLabels:Record<string,string>={active:'Активна',pending:'На модерации',blocked:'Заблокирована',suspended:'Приостановлена'};
const wsLabels:Record<string,string>={AVAILABLE:'Свободен',BUSY:'Занят',OFFLINE:'Офлайн',MAINTENANCE:'На обслуживании'};
export default function AdminBusinessDetail(){
 const {id}=useParams<{id:string}>();const router=useRouter();const [data,setData]=useState<Detail|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState('');
 async function load(){const r=await fetch(`/api/admin/businesses/detail?id=${encodeURIComponent(id)}`);const x=await r.json();if(r.status===403){router.replace('/admin/login');return}if(!r.ok)throw new Error(x.error);setData(x)}
 useEffect(()=>{void load().catch(()=>setError('Не удалось загрузить карточку СТО.'))},[id,router]);
 async function updateStaff(type:'employee'|'workstation',entityId:string,status:string){setBusy(entityId);setError('');try{const r=await fetch('/api/admin/businesses/staff',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({type,id:entityId,status})});const x=await r.json();if(r.status===403){router.replace('/admin/login');return}if(!r.ok)throw new Error(x.error);setData((d)=>d?({...d,employees:type==='employee'?d.employees.map(e=>e.id===entityId?{...e,is_active:status==='active'}:e):d.employees,workstations:type==='workstation'?d.workstations.map(w=>w.id===entityId?{...w,status}:w):d.workstations}):d)}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить')}finally{setBusy('')}}
 if(error&&!data)return <main className="content"><div className="card error">{error}</div><a className="primary" href="/admin/businesses">Вернуться к СТО</a></main>;
 if(!data?.business)return <main className="content"><div className="card">Загружаем карточку СТО…</div></main>;
 const b=data.business;
 return <main className="page"><header className="hero"><div className="hero-inner"><span className="eyebrow">STO NSK · Управление СТО</span><h1>{b.name}</h1><p>{b.address||'Адрес не указан'} · статус <strong>{statusLabels[b.status]||b.status}</strong></p></div></header><div className="content">
 <div className="toolbar"><a className="pill" href="/admin/businesses">← Все СТО</a><a className="pill" href={`/admin/businesses/${b.id}/edit`}>Редактировать</a><a className="pill" href={`/admin/businesses/${b.id}/schedule`}>Расписание</a><a className="pill" href={`/admin/businesses/${b.id}/calendar`}>Календарь записей</a><a className="pill" href={`/novosibirsk/sto/${b.slug}`}>Публичная страница</a></div>{error&&<div className="card error" style={{marginTop:12}}>{error}</div>}
 <div className="feature-grid"><div className="feature"><strong>Рейтинг</strong><span style={{fontSize:28,fontWeight:800}}>★ {b.rating??0}</span><span className="muted">{b.review_count??0} отзывов</span></div><div className="feature"><strong>Услуги</strong><span style={{fontSize:28,fontWeight:800}}>{data.services.length}</span><a className="muted" href={`/admin/businesses/${b.id}/services`}>Управлять →</a></div><div className="feature"><strong>Сотрудники</strong><span style={{fontSize:28,fontWeight:800}}>{data.employees.filter(e=>e.is_active).length}/{data.employees.length}</span><a className="muted" href={`/admin/businesses/${b.id}/manage`}>Управлять →</a></div><div className="feature"><strong>Посты</strong><span style={{fontSize:28,fontWeight:800}}>{data.workstations.filter(w=>w.status==='AVAILABLE').length}/{data.workstations.length}</span><a className="muted" href={`/admin/businesses/${b.id}/manage`}>Управлять →</a></div><div className="feature"><strong>Расписание</strong><span className="muted">Рабочие часы и исключения</span><a className="muted" href={`/admin/businesses/${b.id}/schedule`}>Настроить →</a></div><div className="feature"><strong>Календарь</strong><span className="muted">Записи на выбранный день</span><a className="muted" href={`/admin/businesses/${b.id}/calendar`}>Открыть →</a></div></div>
 <div className="feature-grid" style={{marginTop:16}}><section className="card"><div className="toolbar"><h2>Контакты</h2><span className="pill">{statusLabels[b.status]||b.status}</span></div><div className="service-row"><strong>Телефон</strong><span>{b.phone||'—'}</span></div><div className="service-row"><strong>Email</strong><span>{b.email||'—'}</span></div><div className="service-row"><strong>Адрес</strong><span>{b.address||'—'}</span></div>{b.description&&<p className="muted" style={{marginTop:12}}>{b.description}</p>}</section><section className="card"><h2>Быстрые действия</h2><div style={{display:'grid',gap:8,marginTop:12}}><a className="primary" href={`/admin/businesses/${b.id}/edit`}>Редактировать СТО</a><a className="pill" href={`/admin/businesses/${b.id}/calendar`}>Календарь записей</a><a className="pill" href={`/admin/businesses/${b.id}/schedule`}>Настроить расписание</a><a className="pill" href={`/admin/businesses/${b.id}/services`}>Управление услугами</a><a className="pill" href={`/admin/businesses/${b.id}/manage`}>Команда и посты</a><a className="pill" href={`/business?businessId=${b.id}`}>Кабинет СТО</a><a className="pill" href="/admin/audit">Открыть аудит</a></div></section></div>
 <section className="card" style={{marginTop:16}}><div className="toolbar"><div><h2>Услуги</h2><div className="muted">Активные и архивные услуги СТО</div></div><a className="pill" href={`/admin/businesses/${b.id}/services`}>Управлять</a></div>{data.services.length?data.services.map(s=><div className="service-row" key={s.id}><div style={{flex:1}}><strong>{s.service?.name||'Услуга'}</strong><div className="muted">{s.duration_minutes} мин · {s.price} ₽</div></div><span className="pill">{s.is_active?'Активна':'Выключена'}</span></div>):<div className="empty">Услуг нет.</div>}</section>
 <section className="card" style={{marginTop:16}}><div className="toolbar"><div><h2>Сотрудники</h2><div className="muted">Можно менять активность прямо здесь.</div></div><a className="pill" href={`/admin/businesses/${b.id}/manage`}>Полное управление</a></div>{data.employees.length?data.employees.map(e=><div className="service-row" key={e.id}><div style={{flex:1}}><strong>{e.name}</strong><div className="muted">{e.position||'Должность не указана'}</div></div><select disabled={busy===e.id} value={e.is_active?'active':'inactive'} onChange={ev=>void updateStaff('employee',e.id,ev.target.value)}><option value="active">Активен</option><option value="inactive">Неактивен</option></select></div>):<div className="empty">Сотрудников нет.</div>}</section>
 <section className="card" style={{marginTop:16}}><div className="toolbar"><div><h2>Посты</h2><div className="muted">Можно менять состояние рабочего места прямо здесь.</div></div><a className="pill" href={`/admin/businesses/${b.id}/manage`}>Полное управление</a></div>{data.workstations.length?data.workstations.map(w=><div className="service-row" key={w.id}><div style={{flex:1}}><strong>{w.name}</strong><div className="muted">{wsLabels[w.status]||w.status}</div></div><select disabled={busy===w.id} value={w.status} onChange={ev=>void updateStaff('workstation',w.id,ev.target.value)}>{Object.entries(wsLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>):<div className="empty">Постов нет.</div>}</section>
 <section className="card" style={{marginTop:16}}><div className="toolbar"><div><h2>Последние записи</h2><div className="muted">Последние 25 записей по СТО</div></div><a className="pill" href={`/admin/businesses/${b.id}/calendar`}>Открыть календарь</a><span className="pill">{data.appointments.length}</span></div>{data.appointments.length?data.appointments.map(a=><div className="service-row" key={a.id}><div style={{flex:1}}><strong>{a.user?.display_name||'Клиент'}</strong><div className="muted">{a.service?.service?.name||'Услуга'} · {new Date(a.starts_at).toLocaleString('ru-RU',{dateStyle:'medium',timeStyle:'short'})}</div></div><span className="pill">{labels[a.status]||a.status}</span></div>):<div className="empty">Записей нет.</div>}</section>
 </div><style jsx>{`select{padding:9px 10px;border:1px solid rgba(0,0,0,.12);border-radius:9px;background:#fff}`}</style></main>;
}
