'use client';
import { useEffect,useState } from 'react';
import { useParams,useRouter } from 'next/navigation';

type Service={id:string;price:number;duration_minutes:number;is_active:boolean;service?:{name:string;slug:string}};
export default function AdminBusinessServices(){
 const {id}=useParams<{id:string}>();const router=useRouter();const [items,setItems]=useState<Service[]>([]);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState('');
 const load=async()=>{try{const r=await fetch(`/api/admin/businesses/detail?id=${encodeURIComponent(id)}`);const x=await r.json();if(r.status===403){router.replace('/admin/login');return}if(!r.ok)throw new Error(x.error);setItems(x.services??[])}catch{setError('Не удалось загрузить услуги.')}};
 useEffect(()=>{void load()},[id]);
 const update=async(s:Service)=>{setBusy(s.id);setError('');try{const r=await fetch('/api/admin/businesses/services',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:s.id,price:s.price,duration_minutes:s.duration_minutes,is_active:s.is_active})});const x=await r.json();if(!r.ok)throw new Error(x.error);await load()}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить услугу.')}finally{setBusy(null)}};
 return <main className="page"><header className="hero"><div className="hero-inner"><span className="eyebrow">STO NSK · Admin</span><h1>Услуги СТО</h1><p>Цены, длительность и доступность услуг.</p></div></header><div className="content"><div className="toolbar"><a className="pill" href={`/admin/businesses/${id}`}>← Карточка СТО</a></div>{error&&<div className="card error" style={{marginTop:12}}>{error}</div>}<section className="card" style={{marginTop:16}}>{items.length?items.map(s=><div className="service-row" key={s.id}><div style={{flex:1,minWidth:180}}><strong>{s.service?.name||'Услуга'}</strong><div className="muted">/{s.service?.slug||''}</div></div><label style={{display:'grid',gap:4}}><small className="muted">Цена</small><input type="number" min="0" step="50" value={s.price} onChange={e=>setItems(items.map(x=>x.id===s.id?{...x,price:Number(e.target.value)}:x))}/></label><label style={{display:'grid',gap:4}}><small className="muted">Минуты</small><input type="number" min="1" step="5" value={s.duration_minutes} onChange={e=>setItems(items.map(x=>x.id===s.id?{...x,duration_minutes:Number(e.target.value)}:x))}/></label><label style={{display:'flex',alignItems:'center',gap:6}}><input type="checkbox" checked={s.is_active} onChange={e=>setItems(items.map(x=>x.id===s.id?{...x,is_active:e.target.checked}:x))}/><span>Активна</span></label><button className="pill" disabled={busy===s.id} onClick={()=>void update(s)}>{busy===s.id?'Сохраняем…':'Сохранить'}</button></div>):<div className="empty">Услуг нет.</div>}</section></div><style jsx>{`input[type=number]{width:110px;padding:9px 10px;border:1px solid rgba(0,0,0,.12);border-radius:9px;font:inherit}button{background:#fff;cursor:pointer}@media(max-width:800px){.service-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.service-row>div:first-child{grid-column:1/-1}.service-row button{width:100%}}`}</style></main>;
}
