'use client';

import { useEffect, useMemo, useState } from 'react';

type Car = { id:string; brand:string; model:string; plate_number:string|null };
type User = { id:string; display_name:string|null; phone:string|null };
type Entry={id:string;user_id:string|null;car_id:string|null;status:string;position:number;estimated_wait_minutes:number|null;created_at:string;car:Car|null;user:User|null};
const flow=[['WAITING','В очереди'],['CALLED','Вызван'],['IN_SERVICE','В работе'],['READY','Готов'],['COMPLETED','Завершён']];
const activeStatuses=new Set(['WAITING','CALLED','IN_SERVICE','READY']);

export default function BusinessQueuePage(){
 const [entries,setEntries]=useState<Entry[]>([]),[queueOpen,setQueueOpen]=useState(false),[mode,setMode]=useState('MIXED'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[updating,setUpdating]=useState<string>('');
 const load=async(silent=false)=>{if(!silent)setLoading(true);const r=await fetch('/api/business/queue',{cache:'no-store'});const x=await r.json();if(!r.ok)setError(x.error||'Не удалось загрузить очередь');else{setError('');setQueueOpen(Boolean(x.queue?.is_open));setMode(String(x.queue?.mode||'MIXED'));setEntries((x.queue?.queue_entries??[]).sort((a:Entry,b:Entry)=>a.position-b.position));}if(!silent)setLoading(false)};
 useEffect(()=>{void load();const t=setInterval(()=>void load(true),10000);return()=>clearInterval(t)},[]);
 const active=useMemo(()=>entries.filter(e=>activeStatuses.has(e.status)),[entries]);
 const update=async(id:string,status:string)=>{setError('');setUpdating(id+status);const r=await fetch('/api/business/queue',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({entry_id:id,status})});const x=await r.json();setUpdating('');if(!r.ok)setError(x.error||'Не удалось изменить статус');else await load(true)};
 const totalWait=active.reduce((sum,e)=>sum+Math.max(0,e.estimated_wait_minutes??0),0);
 return <main className="content business-queue-page"><div className="toolbar business-queue-toolbar"><div><span className="pill">STO NSK · Business</span><h1 style={{margin:'8px 0 0'}}>Живая очередь</h1><div className="muted">Автообновление каждые 10 секунд · {mode}</div></div><div className="business-queue-state"><span className={queueOpen?'status green':'status'}>{queueOpen?'● Очередь открыта':'● Очередь закрыта'}</span><button className="pill" onClick={()=>void load()}>Обновить</button></div></div>
 <div className="feature-grid business-queue-kpis" style={{marginBottom:16}}><div className="feature"><strong>Активные</strong><span className="kpi-value">{active.length}</span><span className="muted">автомобилей</span></div><div className="feature"><strong>Ожидание</strong><span className="kpi-value">{active.length?Math.round(totalWait/active.length):0} мин</span><span className="muted">в среднем</span></div><div className="feature"><strong>Следующий</strong><span className="kpi-value">{active[0]?.position??'—'}</span><span className="muted">позиция</span></div></div>
 {error&&<div className="card error" style={{marginBottom:12}}>{error}</div>}
 {loading?<div className="card">Загружаем очередь…</div>:<section className="card business-queue-card">{entries.length===0?<div className="empty"><strong>Очередь пуста</strong><div className="muted">Новые автомобили появятся здесь.</div></div>:entries.map(e=>{const carLabel=e.car?`${e.car.brand} ${e.car.model}`:'Автомобиль';const customer=e.user?.display_name||e.user?.phone||'Клиент';const currentIndex=flow.findIndex(([s])=>s===e.status);const next=currentIndex>=0&&currentIndex<flow.length-1?flow[currentIndex+1]:null;return <article className="business-queue-entry" key={e.id}><div className="queue-position">#{e.position}</div><div className="queue-person"><strong>{carLabel}</strong><div className="muted">{e.car?.plate_number||'Госномер не указан'}</div><div className="muted">{customer}</div><div className="muted">Ожидание: {e.estimated_wait_minutes??'—'} мин</div></div><span className="pill queue-status">{flow.find(x=>x[0]===e.status)?.[1]||e.status}</span><div className="queue-actions">{next&&e.status!=='COMPLETED'?<button className="primary" disabled={updating===e.id+next[0]} onClick={()=>void update(e.id,next[0])}>{updating===e.id+next[0]?'…':next[1]}</button>:null}<button className="pill danger-outline" disabled={updating===e.id+'NO_SHOW'||e.status==='COMPLETED'||e.status==='READY'} onClick={()=>void update(e.id,'NO_SHOW')}>Не явился</button></div></article>})}</section>}
 <section className="section business-queue-help"><div className="feature-grid"><div className="feature"><strong>Вызвать клиента</strong><span className="muted">WAITING → CALLED — следующий шаг автоматически становится основной кнопкой.</span></div><div className="feature"><strong>Начать работу</strong><span className="muted">CALLED → IN_SERVICE переводит автомобиль в работу.</span></div><div className="feature"><strong>Готово</strong><span className="muted">IN_SERVICE → READY → COMPLETED без лишних вариантов статуса.</span></div></div></section>
 </main>;
}