'use client';
import { useEffect,useState } from 'react';
type Overview={metrics:{businesses:number;activeBusinesses:number;users:number;appointments:number;activeQueue:number;reviews:number};businesses:Array<{id:string;name:string;status:string;rating:number|null;created_at:string}>};
const statuses=['active','pending','blocked','suspended'];
export default function AdminPage(){
 const [data,setData]=useState<Overview|null>(null); const [error,setError]=useState('');
 const load=async()=>{const r=await fetch('/api/admin/overview');const x=await r.json();if(!r.ok||x.error)throw new Error(x.error);setData(x)};
 useEffect(()=>{void load().catch(()=>setError('Не удалось загрузить admin dashboard'))},[]);
 const setStatus=async(id:string,status:string)=>{const r=await fetch(`/api/admin/businesses/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status})});if(!r.ok){setError('Не удалось изменить статус СТО');return}await load()};
 if(error&&!data)return <main className="content"><div className="card error">{error}</div></main>;
 if(!data)return <main className="content"><div className="card">Загружаем admin dashboard…</div></main>;
 const m=data.metrics;
 return <main className="page"><header className="hero"><div className="hero-inner"><span className="eyebrow">STO NSK · Super Admin</span><h1>Контроль экосистемы</h1><p>СТО, пользователи, записи, очереди, финансы и модерация в одном интерфейсе.</p></div></header><div className="content"><div className="feature-grid"><div className="feature"><strong>СТО</strong><span style={{fontSize:28,fontWeight:800}}>{m.activeBusinesses}/{m.businesses}</span><span className="muted">активных</span></div><div className="feature"><strong>Пользователи</strong><span style={{fontSize:28,fontWeight:800}}>{m.users}</span></div><div className="feature"><strong>Записи</strong><span style={{fontSize:28,fontWeight:800}}>{m.appointments}</span></div><div className="feature"><strong>Очередь</strong><span style={{fontSize:28,fontWeight:800}}>{m.activeQueue}</span></div><div className="feature"><strong>Отзывы</strong><span style={{fontSize:28,fontWeight:800}}>{m.reviews}</span></div></div><div className="feature-grid" style={{marginTop:16}}><a className="feature" href="/admin/billing" style={{textDecoration:'none'}}><strong>Финансы и монетизация</strong><span className="muted">Комиссия, счета СТО, доступ и реклама →</span></a><a className="feature" href="/admin/analytics" style={{textDecoration:'none'}}><strong>Аналитика</strong><span className="muted">Ключевые показатели платформы →</span></a></div><div className="card" style={{marginTop:16}}><div className="toolbar"><div><h2>Модерация СТО</h2><div className="muted">Управление доступностью в marketplace</div></div><span className="pill">{m.businesses}</span></div>{data.businesses.map(b=><div className="service-row" key={b.id}><span style={{flex:1}}><strong>{b.name}</strong><br/><small className="muted">★ {b.rating||0} · {new Date(b.created_at).toLocaleDateString('ru-RU')}</small></span><select value={b.status} onChange={e=>void setStatus(b.id,e.target.value)}>{statuses.map(s=><option key={s} value={s}>{s}</option>)}</select></div>)}</div></div></main>;
}
