'use client';
import { useEffect, useMemo, useState } from 'react';

type Business={id:string;name:string;platform_access_status:string};
type Invoice={id:string;business_id:string;period_start:string;period_end:string;total:number;status:string;due_at:string|null;business?:{name:string}|null};
type Ledger={business_id:string;base_amount:number;commission_percent:number;commission_amount:number;status:string;period_start:string;period_end:string;business?:{name:string}|null};
type Ad={id:string;title:string;placement:string;status:string;budget:number;price:number;price_model:string;impressions:number;clicks:number;business?:{name:string}|null};
const money=(n:number)=>Number(n||0).toLocaleString('ru-RU',{maximumFractionDigits:2});
const accessLabels:Record<string,string>={active:'Работает',warning:'Предупреждение',suspended:'Приостановлено',removed:'Удалено'};
export default function BillingPage(){
 const [businesses,setBusinesses]=useState<Business[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[ledger,setLedger]=useState<Ledger[]>([]),[ads,setAds]=useState<Ad[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[rates,setRates]=useState<Record<string,string>>({});
 const load=async()=>{const r=await fetch('/api/admin/billing');const x=await r.json();if(!r.ok)throw new Error(x.error||'Нет доступа');setBusinesses(x.businesses??[]);setInvoices(x.invoices??[]);setLedger(x.ledger??[]);setAds(x.ads??[])};
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 const accrued=useMemo(()=>ledger.filter(x=>['accrued','invoiced'].includes(x.status)).reduce((s,x)=>s+Number(x.commission_amount||0),0),[ledger]);
 const update=async(body:any)=>{setBusy(true);setError('');const r=await fetch('/api/admin/billing',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const x=await r.json();setBusy(false);if(!r.ok){setError(x.error||'Операция не выполнена');return}await load()};
 const setRate=(id:string)=>void update({type:'commission',business_id:id,commission_percent:Number(rates[id]||10)});
 const generate=()=>{const d=new Date();const start=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()-1,1)).toISOString().slice(0,10);const end=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),0)).toISOString().slice(0,10);return void update({type:'generate',period_start:start,period_end:end})};
 return <main className="page"><header className="hero"><div className="hero-inner"><span className="eyebrow">STO NSK · Finance</span><h1>Монетизация платформы</h1><p>Комиссия с завершённых заказов, счета СТО, доступ и рекламные размещения.</p></div></header><div className="content">
 {error&&<div className="card error">{error}</div>}
 <div className="feature-grid"><div className="feature"><strong>Начислено комиссий</strong><span style={{fontSize:28,fontWeight:800}}>{money(accrued)} ₽</span><span className="muted">к выставлению</span></div><div className="feature"><strong>Счета</strong><span style={{fontSize:28,fontWeight:800}}>{invoices.length}</span><span className="muted">в системе</span></div><div className="feature"><strong>Реклама</strong><span style={{fontSize:28,fontWeight:800}}>{ads.filter(x=>x.status==='active').length}</span><span className="muted">активных кампаний</span></div></div>
 <div className="card" style={{marginTop:16}}><div className="toolbar"><div><h2>Комиссия по СТО</h2><div className="muted">Процент устанавливается тобой отдельно для каждого СТО.</div></div><button className="primary" disabled={busy} onClick={generate}>Сформировать счёт за прошлый месяц</button></div>{businesses.map(b=><div className="service-row" key={b.id}><div style={{flex:1}}><strong>{b.name}</strong><div className="muted">Доступ: {accessLabels[b.platform_access_status]||b.platform_access_status}</div></div><input style={{maxWidth:90}} inputMode="decimal" placeholder="10" value={rates[b.id]??''} onChange={e=>setRates(v=>({...v,[b.id]:e.target.value}))}/><span>%</span><button className="pill" disabled={busy} onClick={()=>setRate(b.id)}>Сохранить</button><select value={b.platform_access_status} onChange={e=>void update({type:'access',business_id:b.id,platform_access_status:e.target.value})}>{Object.entries(accessLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>)}</div>
 <div className="card"><div className="toolbar"><div><h2>Счета СТО</h2><div className="muted">Оплата возвращает СТО в рабочее состояние.</div></div></div>{invoices.length===0?<div className="empty muted">Счетов пока нет.</div>:invoices.map(i=><div className="service-row" key={i.id}><div style={{flex:1}}><strong>{i.business?.name||i.business_id}</strong><div className="muted">{i.period_start} — {i.period_end} · до {i.due_at?new Date(i.due_at).toLocaleDateString('ru-RU'):'—'}</div></div><strong>{money(i.total)} ₽</strong><select value={i.status} onChange={e=>void update({type:'invoice',invoice_id:i.id,status:e.target.value})}>{['draft','issued','paid','overdue','void'].map(s=><option key={s}>{s}</option>)}</select></div>)}</div>
 <div className="card"><div className="toolbar"><div><h2>Реклама</h2><div className="muted">Платные позиции внутри marketplace.</div></div><span className="pill">{ads.length}</span></div>{ads.length===0?<div className="empty muted">Кампаний пока нет.</div>:ads.map(a=><div className="service-row" key={a.id}><div style={{flex:1}}><strong>{a.title}</strong><div className="muted">{a.business?.name||'Платформа'} · {a.placement} · {a.price_model}</div></div><span>{money(a.price)} ₽</span><span className="pill">{a.status}</span><span className="muted">{a.impressions} показов · {a.clicks} кликов</span></div>)}</div>
 </div></main>;
}
