'use client';

import { useEffect, useState } from 'react';

type Car={id:string;brand:string;model:string;year:number|null;plate_number:string|null;mileage:number|null};
type Appointment={id:string;starts_at:string;ends_at:string;status:string;business:{name:string};service:{price:number;duration_minutes:number;service:{name:string}};car:{brand:string;model:string;plate_number:string|null}};
type Favorite={business_id:string;business:{id:string;name:string;slug:string;rating:number;review_count:number}};
type Review={id:string;business_id:string;appointment_id:string;rating:number;body:string|null;is_published:boolean;business:{name:string}};

const statusLabel:Record<string,string>={PENDING:'Ожидает подтверждения',CONFIRMED:'Подтверждена',ARRIVED:'Клиент прибыл',IN_SERVICE:'Автомобиль в работе',READY:'Готов',COMPLETED:'Завершена',CANCELLED:'Отменена',NO_SHOW:'Неявка'};

export default function AccountPage(){
 const [user,setUser]=useState<any>(null),[cars,setCars]=useState<Car[]>([]),[appointments,setAppointments]=useState<Appointment[]>([]),[favorites,setFavorites]=useState<Favorite[]>([]),[reviews,setReviews]=useState<Review[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [brand,setBrand]=useState(''),[model,setModel]=useState(''),[plate,setPlate]=useState('');
 const [saving,setSaving]=useState(false),[reviewRating,setReviewRating]=useState<Record<string,number>>({}),[reviewBody,setReviewBody]=useState<Record<string,string>>({}),[reviewSaving,setReviewSaving]=useState<string>('');
 const load=async()=>{
   setLoading(true); setError('');
   const me=await fetch('/api/me');
   if(!me.ok){setError('Войдите, чтобы открыть кабинет клиента.');setLoading(false);return;}
   const mx=await me.json();setUser(mx.user);
   const [cx,ax,fx,rx]=await Promise.all([fetch('/api/me/cars'),fetch('/api/me/appointments'),fetch('/api/me/favorites'),fetch('/api/me/reviews')]);
   const [cj,aj,fj,rj]=await Promise.all([cx.json(),ax.json(),fx.json(),rx.json()]);
   if(!cx.ok||!ax.ok||!fx.ok||!rx.ok) setError('Не удалось полностью загрузить кабинет.');
   setCars(cj.cars??[]);setAppointments(aj.appointments??[]);setFavorites(fj.favorites??[]);setReviews(rj.reviews??[]);setLoading(false);
 };
 useEffect(()=>{void load()},[]);
 const addCar=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);const r=await fetch('/api/me/cars',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({brand,model,plate_number:plate})});if(r.ok){setBrand('');setModel('');setPlate('');await load()}else setError('Не удалось добавить автомобиль.');setSaving(false)};
 const cancel=async(id:string)=>{const r=await fetch(`/api/me/appointments/${id}/cancel`,{method:'POST'});if(r.ok) await load(); else setError('Это время уже нельзя отменить.');};
 const removeFavorite=async(id:string)=>{const r=await fetch(`/api/me/favorites?business_id=${encodeURIComponent(id)}`,{method:'DELETE'});if(r.ok)setFavorites(x=>x.filter(f=>f.business_id!==id));};
 const addReview=async(id:string)=>{const rating=reviewRating[id]||0;if(!rating){setError('Выберите оценку от 1 до 5.');return}setReviewSaving(id);const r=await fetch('/api/me/reviews',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({appointment_id:id,rating,body:reviewBody[id]||''})});const x=await r.json();setReviewSaving('');if(!r.ok){setError(x.error==='REVIEW_ALREADY_EXISTS'?'Отзыв для этой записи уже оставлен.':'Не удалось отправить отзыв.');return}await load();};
 if(loading)return <main className="page"><div className="content"><div className="card">Загружаем кабинет…</div></div></main>;
 if(!user)return <main className="page"><header className="hero"><div className="hero-inner"><span className="eyebrow">STO NSK · Кабинет</span><h1>Личный кабинет</h1><p>{error}</p></div></header><div className="content"><div className="card empty"><strong>Авторизация нужна для доступа</strong><div className="muted">Здесь будут ваши автомобили, записи, история, избранное и отзывы.</div></div></div></main>;
 return <main className="page"><header className="hero"><div className="hero-inner"><span className="eyebrow">STO NSK · Личный кабинет</span><h1>{user.display_name||'Ваш кабинет'}</h1><p>{user.phone||user.email||'Управляйте автомобилями и записями в одном месте.'}</p></div></header><div className="content">{error&&<div className="card error" style={{marginBottom:14}}>{error}</div>}<div className="layout"><section className="results"><div className="card"><div className="toolbar"><div><h2>Мои записи</h2><div className="muted">{appointments.length} записей в истории</div></div><span className="pill">История</span></div>{appointments.length===0?<div className="empty"><strong>Записей пока нет</strong><div className="muted">Найдите СТО и выберите свободное время.</div></div>:appointments.map(a=><div className="service-row" key={a.id}><div><strong>{a.business?.name}</strong><div className="muted">{a.service?.service?.name} · {a.car?.brand} {a.car?.model}</div><div className="muted">{new Date(a.starts_at).toLocaleString('ru-RU',{dateStyle:'medium',timeStyle:'short'})}</div></div><div style={{textAlign:'right'}}><div className="pill">{statusLabel[a.status]||a.status}</div>{['PENDING','CONFIRMED'].includes(a.status)&&<button className="pill" style={{marginTop:8,cursor:'pointer'}} onClick={()=>cancel(a.id)}>Отменить</button>}{a.status==='COMPLETED'&&!reviews.some(r=>r.appointment_id===a.id)&&<div style={{marginTop:10,textAlign:'left',minWidth:220}}><div className="muted" style={{marginBottom:5}}>Ваш отзыв</div><select value={reviewRating[a.id]||''} onChange={e=>setReviewRating(v=>({...v,[a.id]:Number(e.target.value)}))} style={{width:'100%',padding:8,border:'1px solid #e2e8f0',borderRadius:8}}><option value="">Оценка</option><option value="5">★★★★★</option><option value="4">★★★★</option><option value="3">★★★</option><option value="2">★★</option><option value="1">★</option></select><textarea value={reviewBody[a.id]||''} onChange={e=>setReviewBody(v=>({...v,[a.id]:e.target.value}))} placeholder="Расскажите о визите" rows={2} style={{width:'100%',marginTop:6,padding:8,border:'1px solid #e2e8f0',borderRadius:8,resize:'vertical'}}/><button className="primary" style={{marginTop:6,width:'100%'}} disabled={reviewSaving===a.id} onClick={()=>addReview(a.id)}>{reviewSaving===a.id?'Отправляем…':'Оставить отзыв'}</button></div>}</div></div>)}</div>
 <div className="card"><div className="toolbar"><div><h2>Мои автомобили</h2><div className="muted">Сохраняйте данные, чтобы записываться быстрее.</div></div><span className="pill">{cars.length}</span></div>{cars.map(c=><div className="service-row" key={c.id}><div><strong>{c.brand} {c.model}</strong><div className="muted">{c.plate_number||'Госномер не указан'} · {c.year||'год не указан'}</div></div><span className="pill">{c.mileage?`${c.mileage.toLocaleString('ru-RU')} км`:'Пробег —'}</span></div>)}<form onSubmit={addCar} style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr auto',gap:8,marginTop:14}}><input placeholder="Марка" value={brand} onChange={e=>setBrand(e.target.value)} required/><input placeholder="Модель" value={model} onChange={e=>setModel(e.target.value)} required/><input placeholder="Госномер" value={plate} onChange={e=>setPlate(e.target.value)}/><button className="primary" disabled={saving}>{saving?'…':'Добавить'}</button></form></div>
 <div className="card"><div className="toolbar"><div><h2>Избранное</h2><div className="muted">СТО, к которым можно вернуться позже.</div></div><span className="pill">{favorites.length}</span></div>{favorites.length===0?<div className="empty"><strong>Пока ничего нет</strong><div className="muted">Добавляйте понравившиеся СТО из marketplace.</div></div>:favorites.map(f=><div className="service-row" key={f.business_id}><div><strong>{f.business?.name}</strong><div className="muted">★ {f.business?.rating||0} · {f.business?.review_count||0} отзывов</div></div><div style={{display:'flex',gap:8}}><a className="pill" href={`/novosibirsk/sto/${f.business?.slug}`}>Открыть</a><button className="pill" onClick={()=>removeFavorite(f.business_id)}>Убрать</button></div></div>)}</div>
 <div className="card"><div className="toolbar"><div><h2>Мои отзывы</h2><div className="muted">После модерации отзыв становится видимым на marketplace.</div></div><span className="pill">{reviews.length}</span></div>{reviews.length===0?<div className="empty"><strong>Отзывов пока нет</strong><div className="muted">Оставьте отзыв после завершённого посещения.</div></div>:reviews.map(r=><div className="service-row" key={r.id}><div><strong>{r.business?.name}</strong><div className="muted">{'★'.repeat(r.rating)} · {r.body||'Без комментария'}</div></div><span className="pill">{r.is_published?'Опубликован':'На модерации'}</span></div>)}</div></section><aside className="card"><span className="pill">Быстрые действия</span><h2 style={{marginTop:12}}>Записаться в СТО</h2><p className="muted">Найдите сервис, выберите услугу и свободное время.</p><a className="primary" style={{display:'inline-block',textDecoration:'none'}} href="/marketplace">Найти СТО</a><div className="section"><div className="feature"><strong>Telegram</strong><span className="muted">Подтверждения, напоминания и очередь доступны после привязки Telegram.</span></div><div className="feature" style={{marginTop:10}}><strong>Живая очередь</strong><span className="muted">Следите за позицией автомобиля в реальном времени.</span></div></div></aside></div></div></main>;
}
