'use client';
import { useEffect,useMemo,useState } from 'react';

type Car={id:string;brand:string;model:string;year:number|null;plate_number:string|null;mileage:number|null};
type Appointment={id:string;business_id:string;starts_at:string;ends_at:string;status:string;business?:{name:string;slug:string};service?:{id:string;price:number;duration_minutes:number;service?:{name:string}};car?:{brand:string;model:string;plate_number:string|null};workstation?:{id:string;name:string;status:string}|null;employee?:{id:string;name:string;position:string|null}|null};
type Slot={slot_start:string;slot_end:string;available_workstations:number};
type Favorite={business_id:string;business?:{name:string;slug:string;rating:number;review_count:number}};
type Review={id:string;appointment_id:string;rating:number;body:string|null;is_published:boolean;business?:{name:string}};
const labels:Record<string,string>={PENDING:'Ожидает подтверждения',CONFIRMED:'Подтверждена',ARRIVED:'Клиент прибыл',IN_SERVICE:'В работе',READY:'Готов',COMPLETED:'Завершена',CANCELLED:'Отменена',NO_SHOW:'Неявка'};
const TZ='Asia/Novosibirsk';
const dateKey=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ}).format(d);
const formatSlot=(v:string)=>new Intl.DateTimeFormat('ru-RU',{timeZone:TZ,hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const formatDate=(v:string)=>new Intl.DateTimeFormat('ru-RU',{timeZone:TZ,dateStyle:'medium'}).format(new Date(`${v}T12:00:00`));

export default function AccountPage(){
 const [user,setUser]=useState<any>(null),[cars,setCars]=useState<Car[]>([]),[appointments,setAppointments]=useState<Appointment[]>([]),[favorites,setFavorites]=useState<Favorite[]>([]),[reviews,setReviews]=useState<Review[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[brand,setBrand]=useState(''),[model,setModel]=useState(''),[plate,setPlate]=useState(''),[editId,setEditId]=useState<string|null>(null),[edit,setEdit]=useState<Partial<Car>>({}),[saving,setSaving]=useState(false);
 const [reschedule,setReschedule]=useState<Appointment|null>(null),[rescheduleDate,setRescheduleDate]=useState(dateKey(new Date(Date.now()+86400000))),[slots,setSlots]=useState<Slot[]>([]),[slotsLoading,setSlotsLoading]=useState(false),[selectedSlot,setSelectedSlot]=useState('');
 const load=async()=>{setLoading(true);const me=await fetch('/api/me');if(!me.ok){setError('Войдите, чтобы открыть кабинет клиента.');setLoading(false);return}const m=await me.json();setUser(m.user);const rs=await Promise.all(['/api/me/cars','/api/me/appointments','/api/me/favorites','/api/me/reviews'].map(x=>fetch(x).then(r=>r.json())));setCars(rs[0].cars??[]);setAppointments(rs[1].appointments??[]);setFavorites(rs[2].favorites??[]);setReviews(rs[3].reviews??[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const add=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);const r=await fetch('/api/me/cars',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({brand,model,plate_number:plate})});if(r.ok){setBrand('');setModel('');setPlate('');await load()}else setError('Не удалось добавить автомобиль.');setSaving(false)};
 const save=async()=>{if(!editId)return;setSaving(true);const r=await fetch('/api/me/cars',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:editId,...edit})});if(r.ok){setEditId(null);await load()}else setError('Не удалось сохранить автомобиль.');setSaving(false)};
 const remove=async(id:string)=>{const r=await fetch(`/api/me/cars?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(r.ok)await load();else setError('Автомобиль нельзя удалить, если он используется в истории записей.');};
 const cancel=async(id:string)=>{const r=await fetch(`/api/me/appointments/${id}/cancel`,{method:'POST'});if(r.ok)await load();else setError('Эту запись уже нельзя отменить.')};
 const openReschedule=async(a:Appointment)=>{setError('');setReschedule(a);setRescheduleDate(dateKey(new Date(new Date(a.starts_at).getTime()+86400000)));setSelectedSlot('');setSlotsLoading(true);try{const r=await fetch(`/api/availability?businessId=${a.business_id}&businessServiceId=${a.service?.id}&date=${dateKey(new Date(new Date(a.starts_at).getTime()+86400000))}`);const x=await r.json();setSlots(r.ok?(x.slots??[]):[]);if(!r.ok)setError(x.error||'Не удалось загрузить свободное время.')}catch{setError('Не удалось загрузить свободное время.')}finally{setSlotsLoading(false)}};
 const changeRescheduleDate=async(date:string)=>{if(!reschedule?.service?.id)return;setRescheduleDate(date);setSelectedSlot('');setSlotsLoading(true);try{const r=await fetch(`/api/availability?businessId=${reschedule.business_id}&businessServiceId=${reschedule.service.id}&date=${date}`);const x=await r.json();setSlots(r.ok?(x.slots??[]):[]);if(!r.ok)setError(x.error||'Не удалось загрузить свободное время.')}catch{setError('Не удалось загрузить свободное время.')}finally{setSlotsLoading(false)}};
 const saveReschedule=async()=>{if(!reschedule||!selectedSlot)return;setSaving(true);const r=await fetch(`/api/me/appointments/${reschedule.id}/reschedule`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({starts_at:selectedSlot})});const x=await r.json();setSaving(false);if(!r.ok){setError(x.error||'Не удалось перенести запись.');return}setReschedule(null);setSelectedSlot('');await load()};
 const upcoming=useMemo(()=>appointments.filter(a=>['PENDING','CONFIRMED'].includes(a.status)),[appointments]);
 if(loading)return <main className="page account-page"><div className="content"><div className="card">Загружаем кабинет…</div></div></main>;
 if(!user)return <main className="page account-page"><div className="content"><div className="card empty"><h2>Личный кабинет</h2><p>{error}</p><a className="primary" href="/auth?returnTo=/account&mode=login">Войти</a></div></div></main>;
 return <main className="page account-page"><header className="hero"><div className="hero-inner"><span className="eyebrow">STO NSK · Личный кабинет</span><h1>{user.display_name||'Ваш кабинет'}</h1><p>{user.phone||user.email||'Управляйте автомобилями и записями.'}</p></div></header><div className="content">{error&&<div className="card error">{error}</div>}<div className="layout"><section className="results">
 <div className="card"><div className="toolbar"><div><h2>Мои записи</h2><div className="muted">{upcoming.length?`${upcoming.length} предстоящих визита`:'Будущих визитов пока нет'}</div></div><span className="pill">{appointments.length}</span></div>{appointments.length===0?<div className="empty">Записей пока нет.</div>:appointments.map(a=><div className="service-row account-row" key={a.id}><div style={{flex:1,minWidth:220}}><strong>{a.business?.name||'СТО'}</strong><div className="muted">{a.service?.service?.name||'Услуга'} · {a.car?.brand} {a.car?.model}{a.car?.plate_number?` · ${a.car.plate_number}`:''}</div><div className="muted">{new Date(a.starts_at).toLocaleString('ru-RU',{dateStyle:'medium',timeStyle:'short'})}</div><div className="muted">{a.workstation?.name?`Пост: ${a.workstation.name}`:'Пост будет назначен'}{a.employee?.name?` · ${a.employee.name}`:''}</div></div><div className="account-status"><span className="pill">{labels[a.status]||a.status}</span>{['PENDING','CONFIRMED'].includes(a.status)&&<><button className="pill" onClick={()=>void openReschedule(a)}>Перенести</button><button className="pill" onClick={()=>void cancel(a.id)}>Отменить</button></>}</div></div>)}</div>
 <div className="card"><div className="toolbar"><div><h2>Мои автомобили</h2><div className="muted">Добавьте автомобиль один раз — и запись станет быстрее</div></div><span className="pill">{cars.length}</span></div>{cars.map(c=>editId===c.id?<div className="card" key={c.id}><div className="account-form-grid"><input value={String(edit.brand??'')} onChange={e=>setEdit(v=>({...v,brand:e.target.value}))} placeholder="Марка"/><input value={String(edit.model??'')} onChange={e=>setEdit(v=>({...v,model:e.target.value}))} placeholder="Модель"/><input value={String(edit.plate_number??'')} onChange={e=>setEdit(v=>({...v,plate_number:e.target.value}))} placeholder="Госномер"/><input value={edit.year==null?'':String(edit.year)} onChange={e=>setEdit(v=>({...v,year:e.target.value===''?null:Number(e.target.value)}))} placeholder="Год" inputMode="numeric"/><input value={edit.mileage==null?'':String(edit.mileage)} onChange={e=>setEdit(v=>({...v,mileage:e.target.value===''?null:Number(e.target.value)}))} placeholder="Пробег" inputMode="numeric"/></div><div className="account-actions"><button className="primary" disabled={saving} onClick={()=>void save()}>Сохранить</button><button className="pill" onClick={()=>setEditId(null)}>Отмена</button></div></div>:<div className="service-row account-row" key={c.id}><div><strong>{c.brand} {c.model}</strong><div className="muted">{c.plate_number||'Госномер не указан'} · {c.year||'год не указан'}</div></div><span className="pill">{c.mileage?`${c.mileage.toLocaleString('ru-RU')} км`:'Пробег —'}</span><div className="account-actions"><button className="pill" onClick={()=>{setEditId(c.id);setEdit(c)}}>Изменить</button><button className="pill danger-button" onClick={()=>void remove(c.id)}>Удалить</button></div></div>)}<form onSubmit={add} className="account-add-form"><input placeholder="Марка" value={brand} onChange={e=>setBrand(e.target.value)} required/><input placeholder="Модель" value={model} onChange={e=>setModel(e.target.value)} required/><input placeholder="Госномер" value={plate} onChange={e=>setPlate(e.target.value)}/><button className="primary" disabled={saving}>Добавить автомобиль</button></form></div>
 <div className="card"><div className="toolbar"><h2>Избранное</h2><span className="pill">{favorites.length}</span></div>{favorites.map(f=><div className="service-row account-row" key={f.business_id}><strong>{f.business?.name}</strong><span className="muted">★ {f.business?.rating||0} · {f.business?.review_count||0} отзывов</span><a className="pill" href={`/novosibirsk/sto/${f.business?.slug}`}>Открыть</a></div>)}{favorites.length===0&&<div className="empty">Избранных СТО пока нет.</div>}</div>
 <div className="card"><div className="toolbar"><h2>Мои отзывы</h2><span className="pill">{reviews.length}</span></div>{reviews.map(r=><div className="service-row account-row" key={r.id}><div><strong>{r.business?.name}</strong><div className="muted">{'★'.repeat(r.rating)} · {r.body||'Без комментария'}</div></div><span className="pill">{r.is_published?'Опубликован':'На модерации'}</span></div>)}{reviews.length===0&&<div className="empty">Отзывов пока нет.</div>}</div>
 </section><aside className="card account-quick"><span className="pill">Быстрые действия</span><h2>Записаться в СТО</h2><p className="muted">Найдите сервис, выберите услугу и свободное время.</p><a className="primary" href="/marketplace">Найти СТО</a></aside></div></div>
 {reschedule&&<div className="booking-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setReschedule(null)}}><section className="booking-sheet" role="dialog" aria-modal="true" aria-label="Перенос записи" onMouseDown={e=>e.stopPropagation()}><div className="sheet-header"><div><span className="booking-label">Перенос записи</span><h2>{reschedule.business?.name}</h2><div className="muted">{reschedule.service?.service?.name} · текущая дата {new Date(reschedule.starts_at).toLocaleString('ru-RU',{dateStyle:'medium',timeStyle:'short'})}</div></div><button className="sheet-close" onClick={()=>setReschedule(null)}>×</button></div><div className="booking-block"><div className="booking-title">Новая дата</div><input type="date" min={dateKey(new Date())} value={rescheduleDate} onChange={e=>void changeRescheduleDate(e.target.value)} /><div className="booking-title" style={{marginTop:14}}>Свободное время</div>{slotsLoading?<div className="empty">Загружаем свободное время…</div>:slots.length===0?<div className="empty">На эту дату свободных слотов нет.</div>:<div className="slot-grid">{slots.map(s=><button key={s.slot_start} className={`slot-option ${selectedSlot===s.slot_start?'selected':''}`} onClick={()=>setSelectedSlot(s.slot_start)}>{formatSlot(s.slot_start)}</button>)}</div>}<div className="muted" style={{marginTop:12}}>Выбранная дата: {formatDate(rescheduleDate)}</div></div><div className="sheet-actions"><button className="pill" onClick={()=>setReschedule(null)}>Закрыть</button><button className="primary" disabled={!selectedSlot||saving} onClick={()=>void saveReschedule()}>Перенести запись</button></div></section></div>}
 </main>;
}
