'use client';

import { useEffect, useState } from 'react';

type Service={id:string;service_id:string;price:number;min_price:number|null;duration_minutes:number;service:{id:string;name:string;slug:string;category:{id:string;name:string}|null}|null};
type Catalog={id:string;name:string};

export default function BusinessServicesPage(){
 const [services,setServices]=useState<Service[]>([]),[catalog,setCatalog]=useState<Catalog[]>([]),[serviceId,setServiceId]=useState(''),[price,setPrice]=useState(''),[duration,setDuration]=useState('60'),[minPrice,setMinPrice]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{const [s,c]=await Promise.all([fetch('/api/business/services'),fetch('/api/services')]);const sj=await s.json(),cj=await c.json();if(s.ok)setServices(sj.services??[]);else setError(sj.error||'Не удалось загрузить услуги');if(c.ok)setCatalog(cj.services??[])};
 useEffect(()=>{void load()},[]);
 const add=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/business/services',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({service_id:serviceId,price:Number(price),min_price:minPrice?Number(minPrice):null,duration_minutes:Number(duration)})});const x=await r.json();if(!r.ok)setError(x.error||'Не удалось создать услугу');else{setServiceId('');setPrice('');setMinPrice('');await load()}setBusy(false)};
 return <main className="page"><header className="hero"><div className="hero-inner"><span className="eyebrow">STO NSK · Business</span><h1>Услуги и цены</h1><p>Один глобальный каталог, отдельная цена и длительность для вашего СТО.</p></div></header><div className="content"><div className="layout"><section className="results"><div className="card"><div className="toolbar"><div><h2>Активные услуги</h2><div className="muted">{services.length} предложений</div></div><span className="pill">Прайс</span></div>{services.length===0?<div className="empty muted">Добавьте первую услугу.</div>:services.map(s=><div className="service-row" key={s.id}><div><strong>{s.service?.name}</strong><div className="muted">{s.service?.category?.name||'Без категории'} · {s.duration_minutes} мин</div></div><div style={{textAlign:'right'}}><strong>от {Number(s.price).toLocaleString('ru-RU')} ₽</strong>{s.min_price&&<div className="muted">минимум {Number(s.min_price).toLocaleString('ru-RU')} ₽</div>}</div></div>)}</div></section><aside className="card"><h2>Добавить услугу</h2><form onSubmit={add} style={{display:'grid',gap:10,marginTop:12}}><select value={serviceId} onChange={e=>setServiceId(e.target.value)} required><option value="">Выберите услугу</option>{catalog.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input inputMode="decimal" placeholder="Цена, ₽" value={price} onChange={e=>setPrice(e.target.value)} required/><input inputMode="decimal" placeholder="Мин. цена, ₽" value={minPrice} onChange={e=>setMinPrice(e.target.value)}/><input inputMode="numeric" placeholder="Длительность, мин" value={duration} onChange={e=>setDuration(e.target.value)} required/><button className="primary" disabled={busy}>{busy?'Сохраняем…':'Добавить услугу'}</button></form>{error&&<div className="error" style={{marginTop:12}}>{error}</div>}</aside></div></div></main>;
}
